let name="demo";
let val1=23;
let val2=34.5;
let isdataavail=true;
let nodata=null;
let a;
let b=2;
let c=3;
console.log(typeof(name));
console.log(val1);
console.log(val2);
console.log(isdataavail);
console.log(nodata);
console.log(typeof(a));
console.log(b**c);
